name: Close Weekly Retrospective Issues

on:
  schedule:
    - cron: '59 14 * * 0' # UTC 시간으로 일요일 오후 2시 59분에 실행, KST로는 일요일 23:59

permissions:
  issues: write
  contents: read

jobs:
  close_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Close issues with specific label
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.ISSUE_TOKEN}}
          script: |
            const github = require('@actions/github');
            const { owner, repo } = github.context.repo;
            const label = ['KPT', 'retrospective'];
            const state = 'open';
            const issues = await github.rest.issues.listForRepo({
              owner,
              repo,
              labels: labels.join(','),
              state,
            });
            const issueNumbers = issues.data.map(issue => issue.number);

            for (const number of issueNumbers) {
              await github.rest.issues.update({
                owner,
                repo,
                issue_number: number,
                state: 'closed',
              });
              console.log(`Closed issue number: ${number}`);
            }
